name: 'Terraform'
description: "Execute terraform"

 # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
inputs:
  working_dir:
    description: "Pass the terraform working directory"
    required: true
  terraform_action:
    description: " Pass the terraform action to run terraform commands"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Terraform Fmt
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.2
        tf_actions_subcommand: 'fmt'
        tf_actions_working_dir: ${{ inputs.working_dir }}
        tf_actions_comment: true
        args: '-check -recursive'
      
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.2
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: ${{ inputs.working_dir }}
        tf_actions_comment: true
  
    - name: Terraform plan
      uses: hashicorp/terraform-github-actions@master
      with:
        
        tf_actions_version: 1.9.2
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: ${{ inputs.working_dir }}
        tf_actions_comment: true

    
    - name: Terraform apply
      if: ${{ inputs.terraform_action == 'apply' }}
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.2
        tf_actions_subcommand: ${{ inputs.terraform_action }}
        tf_actions_working_dir: ${{ inputs.working_dir }}
        tf_actions_comment: true
        args: '-auto-approve'

    - name: Terraform destroy
      if: ${{ inputs.terraform_action == 'destroy' }}
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.9.2
        tf_actions_subcommand: ${{ inputs.terraform_action }}
        tf_actions_working_dir: ${{ inputs.working_dir }}
        tf_actions_comment: true
        args: '-auto-approve'